apiVersion: v1
kind: Secret
metadata:
  name: mysql-db-password
type: Opaque
data: 
  db-password: YWJmb25nYW5nMjM3

# Base64 of abfongang237
# https://www.base64encode.org/
# Base64 of abfongang237 is YWJmb25nYW5nMjM3